import './globals.css'

import Modal from 'components/common/Modal'
import BaseLayout from 'components/layout/Layout'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ModalProvider from 'providers/ModalProvider'
import RecoilProvider from 'providers/RecoilProvider'
import TanstackProvider from 'providers/TanstackProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilProvider>
          <TanstackProvider>
            <BaseLayout>{children}</BaseLayout>
            <Modal />
          </TanstackProvider>
        </RecoilProvider>
        <ModalProvider />
      </body>
    </html>
  )
}
